### ISSUE TITLE
Godot 4.3 audio not continuing across scenes, instead it restarts

### ISSUE THREAD

**Issue by brylie** [Maaack/Godot-Music-Controller#3]
I've followed the instructions for setting the `AudioStreamPlayer` on all scenes with a common bus and enabling autoplay for all `AudioStreamPlayer` instances. However,  the audio is restarted each time a scene loads instead of continuing across scenes.

> Use AudioStreamPlayer nodes in your scenes to play background music as normal. Make sure a matching audio bus is set (Music by default), and that autoplay is set to true.

Has this plugin been tested on Godot 4.3?

**Comment by Maaack** [comment]
Thanks for reporting the issue. Are you experiencing this issue in the editor, or with web exports?

There is currently a known bug with web exports on 4.3, and the current recommendation is to build with 4.4-dev*.
https://github.com/Maaack/Godot-Game-Template/issues/133

**Comment by Maaack** [comment]
Re-tested the music controller in a new project, and I'm getting expected behavior. I added the bg music players to two scenes with the same song on both, and added the `Music` audio bus. First scene transitions to next scene after 5 seconds.
```
func _ready():
	await get_tree().create_timer(5).timeout
	get_tree().change_scene_to_file("res://menu.tscn")
```
The track continues playing for me when testing in the editor.

**Comment by brylie** [comment]
I was experiencing the issue in the editor. Perhaps I missed some step for configuration, as I wasn't really sure what to do based on the README. I'll link to a video where I tried to get it working so you can see the steps I took and any possible oversight.

**Comment by brylie** [comment]
Here's a recording of today's code session, where I tried adding the library. Link to the relevant timestamp: https://youtu.be/Qa8ALw1VLDk?t=678

**Comment by Maaack** [comment]
Thanks for making the video and sharing it! It's really helpful for me to see where people stumble. I'm mostly scrubbing through to find relevant bits, apologies if I missed something.

I see that you eventually added the "Music" bus, which should help based on the defaults of the plugin. I will add that step to the documentation.

I'd check that the root node in `ProjectMusicController.tscn` (in addons/) is still set to "Music" bus.

![image](https://github.com/user-attachments/assets/d545a327-674e-4f33-8e75-ff62195742d5)

Also that it shows up in your project's autoloads.

![image](https://github.com/user-attachments/assets/17e88a60-6770-4bc9-b079-2b6565279ddb)

You could also try replacing your audio stream players with instances of the `BackgroundMusicPlayer`, even though those are just audio stream players with the audio bus and autoplay set.

Let me know if you are still having trouble.

Tangentially related, I think it is best-practice to include `addons/` in a Godot project's `.gitignore` file.

**Comment by Maaack** [comment]
Here's a zip of my test project with the plugin, too.

[test-music.zip](https://github.com/user-attachments/files/18142089/test-music.zip)

**Comment by Maaack** [comment]
Another place to check is the remote tab in the Scene tree view while running the project in the editor. I'd verify that the MusicController is there, and not getting removed somehow.
![image](https://github.com/user-attachments/assets/d98ab73e-2d7a-4188-830d-97d1cedcceb6)

**Comment by brylie** [comment]
Yeah, this probably boils down to me being very new to Godot and needing step-by-step instructions for setting up the audio controller. I.e., not assuming any prior or tacit knowledge. :-)

**Comment by brylie** [comment]
Hm. I followed the instructions exactly as written in the README on an existing project. I've also verified that 
- the audio bus is `Music`, 
- Added the `ProjectMusicController` autoload
- added an `AudioStreamPlayer` to each scene with the MP3 file configured (correct audio bus and autoplay setting)
    -  also tried the `BackgroundMusicPlayer` node as a pre-configured alternative to `AudioStreamPlayer`
- ran the game and verified the `ProjectMusicController` was visible under the Remote tab

For whatever reason, the track is restarting each scene. Do the audio players need to share a common Stream resource so the ProjectMusicController "knows" to continue the track?

Here's a branch with my latest experiment:

https://github.com/OutwardLightStudio/nexus/pull/37/files

**Comment by brylie** [comment]
I think the bug is because I am dragging and dropping the audio stream resource onto the AudioStreamPlayer Stream field.

https://github.com/user-attachments/assets/4e6f00de-b11f-49d4-bfd3-204f8502a374

When I drag and drop the resource there, the track restarts every new scene, even though it is the same track.

However, when I click the drop-down, then Quick Load, and select the resource, things work correctly!

https://github.com/user-attachments/assets/fd560ba2-3c71-4aa1-8fd0-23712469a6d5

**Comment by Maaack** [comment]
I got emails about new messages, but I'm not seeing them here. I just wanted to be sure that this is confirmed working, and if there's any more documentation or fixes that I can add. Thanks!

**Comment by brylie** [comment]
Yes, I was able to get it to work. Thank you for your help and for updating the documentation :-)
